package signal

import (
	"time"

	"github.com/1jehuang/backtest/internal/market"
)

// SignalType represents the type of a trading signal.
type SignalType string

const (
	SignalTypeLongEntry  SignalType = "long_entry"
	SignalTypeLongExit   SignalType = "long_exit"
	SignalTypeShortEntry SignalType = "short_entry"
	SignalTypeShortExit  SignalType = "short_exit"
)

// Signal represents a trading signal generated by a strategy.
type Signal struct {
	Type      SignalType
	Symbol    market.Symbol
	Timestamp time.Time
	Price     float64
	Reason    string
	Strength  float64 // Optional: signal strength/confidence (0-1)
}
